---  #This playbook installs webservers
- hosts: all
  connection: ssh
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Install webserver
      yum: name=elinks state=installed
      notify:
      - httpd

    - name: Install PHP
      yum: name=php state=installed

    - name: Install DB
      yum:
        name: mysql-server
        state: installed
    
    - name: Install mysql client
      yum:
        name: mysql
        state: installed 


  handlers:
    - name: httpd
      service: name=httpd state=restarted enabled=yes
